print("I wake up and fold my blanket.")
print("I brush my teeth and go downstairs to eat breakfast.")
print("I go for a run and shower once I get back.")
print("I go out with my friends to play basketball at the park.")
print("I come home and eat lunch.")
print("I go to the gym with my friend.")
print("I come home and play video games with my friends.")
print("I complete all my homework.")
print("I eat dinner.")
print("I brush my teeth and go to sleep.")